version:  '3.7'
services:
    lap:
        build:
            context: .
            dockerfile: .docker/lap/Dockerfile
        restart: on-failure
        volumes:
            - '.:/var/www/plademar'
        ports:
            - 80:80
            - 443:443
            - 8080:8080
